export const providers_link = {
  'AMC Plus Apple TV Channel ': "https://tv.apple.com/",
  'AMC+': "https://www.amcplus.com/",
  'AMC+ Amazon Channel': "https://www.primevideo.com/",
  'ARROW': "https://www.arrow-player.com/",
  'Acontra Plus': "https://www.acontra.no/",
  'Acontra Plus Amazon Channel': "https://www.primevideo.com/",
  'Allente': "https://www.allente.no/",
  'Amazon Arthaus Channel': "https://www.primevideo.com/",
  'Amazon Prime Video': "https://www.primevideo.com/",
  'Amazon Prime Video Free with Ads': "https://www.primevideo.com/",
  'Amazon Prime Video with Ads': "https://www.primevideo.com/",
  'Amazon Video': "https://www.primevideo.com/",
  'Apple TV': "https://tv.apple.com/",
  'AroVision Aotearoa': "https://arovision.nz/",
  'Arrow Video Amazon Channel': "https://www.primevideo.com/",
  'Arthaus+': "https://www.arthouse.plus/",
  'Arthaus+ Apple TV channel': "https://tv.apple.com/",
  'Arthouse CNMA Amazon Channel': "https://www.primevideo.com/",
  'BFI Player': "https://player.bfi.org.uk/",
  'BFI Player Amazon Channel': "https://www.primevideo.com/",
  'BFI Player Apple TV Channel': "https://tv.apple.com/",
  'BINGE': "https://binge.com.au/",
  'Bbox VOD': "https://www.bouyguestelecom.fr/",
  'Beamafilm': "https://beamafilm.com/",
  'Blockbuster': "https://www.blockbuster.com/",
  'CANAL+': "https://www.canalplus.com/",
  'CG Collection Amazon channel': "https://www.primevideo.com/",
  'CG tv': "https://cgtv.tv/",
  'CTV': "https://www.ctv.ca/",
  'Canal VOD': "https://www.canalvod.com/",
  'Canal+': "https://www.canalplus.com/",
  'Catchplay': "https://www.catchplay.com/",
  'Cine+ OCS Amazon Channel ': "https://www.primevideo.com/",
  'CineMember': "https://www.cinemember.nl/",
  'Cinefil Wow Plus Amazon Channel': "https://www.primevideo.com/",
  'Cinemas a la Demande': "https://www.cinemasalademande.com/",
  'Cineplex': "https://cineplex.com/",
  'Claro tv+': "https://www.clarotv.com/",
  'Claro video': "https://www.clarovideo.com/",
  'Crave': "https://www.crave.ca/",
  'Criterion Channel': "https://www.criterionchannel.com/",
  'Curzon Home Cinema': "https://www.curzonhomecinema.com/",
  'Disney Plus': "https://www.disneyplus.com/",
  'Draken Films': "https://www.drakenfilm.se/",
  'Edisonline': "https://www.edisonline.it/",
  'Elisa Viihde': "https://elisaviihde.fi/",
  'FILMO': "https://www.filmo.tv/",
  'Fandango At Home': "https://www.fandangoathome.com/",
  'Fetch TV': "https://www.fetchtv.com.au/",
  'Film1': "https://www.film1.nl/",
  'FilmBox+': "https://filmboxplus.com/",
  'Filmin': "https://www.filmin.es/",
  'Filmin Plus': "https://www.filmin.es/",
  'Filmlegenden Amazon Channel': "https://www.primevideo.com/",
  'Filmo Amazon Channel': "https://www.primevideo.com/",
  'Foxtel Now': "https://www.foxtel.com.au/",
  'Freenet meinVOD': "https://www.freenet.de/",
  'Globoplay': "https://globoplay.globo.com/",
  'Go3': "https://go3.lv/",
  'Google Play Movies': "https://play.google.com/store/movies",
  'HBO Max': "https://www.max.com/",
  'HBO Max  Amazon Channel': "https://www.primevideo.com/",
  'HBO Max Amazon Channel': "https://www.primevideo.com/",
  'Hotstar': "https://www.hotstar.com/",
  'Hulu': "https://www.hulu.com/",
  'Infinity Selection Amazon Channel': "https://www.primevideo.com/",
  'Infinity+': "https://www.infinitytv.it/",
  'Ivi': "https://www.ivi.ru/",
  'JioHotstar': "https://www.hotstar.com/in",
  'Joyn': "https://www.joyn.de/",
  'KADOKAWA channel Amazon Channel': "https://www.primevideo.com/",
  'KKTV': "https://www.kktv.me/",
  'KPN': "https://www.kpn.com/",
  'Kinopoisk': "https://hd.kinopoisk.ru/",
  'KlikFilm': "https://www.klikfilm.com/",
  'LaCinetek': "https://www.lacinetek.com/",
  'Lepsi TV': "https://lepsi.tv/",
  'Lionsgate Play': "https://www.lionsgateplay.com/",
  'Lionsgate Play Amazon Channel': "https://www.primevideo.com/",
  'Lionsgate Play Apple TV Channel': "https://tv.apple.com/",
  'MGM Plus': "https://www.mgmplus.com/",
  'MGM Plus Roku Premium Channel': "https://therokuchannel.roku.com/",
  'MTV Katsomo': "https://www.mtv.fi/",
  'MUBI': "https://mubi.com/",
  'MUBI Amazon Channel': "https://www.primevideo.com/",
  'Magenta TV': "https://www.telekom.de/",
  'Magenta TV+': "https://www.telekom.de/",
  'MagentaTV': "https://www.telekom.de/",
  'Mediaset Infinity': "https://mediasetinfinity.mediaset.it/",
  'Mercado Play': "https://www.mercadoplay.com/",
  'Molotov TV': "https://www.molotov.tv/",
  'More TV': "https://more.tv/",
  'Movistar Plus+': "https://www.movistarplus.es/",
  'Movistar Plus+ Ficción Total ': "https://www.movistarplus.es/",
  'MovistarTV': "https://www.movistar.com.co/",
  'Neon TV': "https://www.neontv.co.nz/",
  'Netflix': "https://www.netflix.com/",
  'Netflix Standard with Ads': "https://www.netflix.com/",
  'Nexo Plus': "https://www.nexoplus.pe/",
  'Now TV': "https://www.nowtv.com/",
  'Now TV Cinema': "https://www.nowtv.com/",
  'OSN+': "https://www.osnplus.com/",
  'Okko': "https://okko.tv/",
  'Oneplay': "https://oneplay.bg/",
  'Orange VOD': "https://vod.orange.fr/",
  'Paramount Plus': "https://www.paramountplus.com/",
  'Paramount Plus Basic with Ads': "https://www.paramountplus.com/",
  'Paramount Plus Premium': "https://www.paramountplus.com/",
  'Paramount+ Amazon Channel': "https://www.primevideo.com/",
  'Pathé Thuis': "https://www.pathe-thuis.nl/",
  'Philo': "https://www.philo.com/",
  'Picl': "https://www.picl.fr/",
  'Player': "https://player.pl/",
  'Plex': "https://watch.plex.tv/",
  'Pluto TV': "https://pluto.tv/",
  'Polsat Box Go': "https://polsatboxgo.pl/",
  'Premiere Max': "https://www.premiere.de/",
  'Premiery Canal+': "https://www.canalplus.com/",
  'RTL+': "https://www.rtlplus.com/",
  'Rai Play': "https://www.raiplay.it/",
  'Rakuten TV': "https://rakuten.tv/",
  'Reserva Imovision Amazon Channel': "https://www.primevideo.com/",
  'Runtime': "https://www.runtime.tv/",
  'Ruutu': "https://www.ruutu.fi/",
  'SF Anytime': "https://www.sfanytime.com/",
  'STARZPLAY': "https://www.starzplay.com/",
  'ScreenPix Amazon Channel ': "https://www.primevideo.com/",
  'ScreenPix Apple TV Channel': "https://tv.apple.com/",
  'ShowMax': "https://www.showmax.com/",
  'Shudder': "https://www.shudder.com/",
  'Shudder Amazon Channel': "https://www.primevideo.com/",
  'Shudder Apple TV Channel': "https://tv.apple.com/",
  'Sky': "https://www.sky.com/",
  'Sky Go': "https://www.skygo.co.uk/",
  'Sky Store': "https://www.skystore.com/",
  'Sky X': "https://www.skyx.sky.de/",
  'SkyShowtime': "https://www.skyshowtime.com/",
  'Sony Pictures Amazon Channel': "https://www.primevideo.com/",
  'Sooner': "https://www.sooner.tv/",
  'Spectrum On Demand': "https://www.spectrum.com/",
  'Stan': "https://www.stan.com.au/",
  'Starz Amazon Channel': "https://www.primevideo.com/",
  'Strim': "https://strim.io/",
  'TELETOON+ Amazon Channel': "https://www.primevideo.com/",
  'TOD': "https://www.tod.tv/",
  'TV 2': "https://www.tv2.no/",
  'TV 2 Play': "https://play.tv2.no/",
  'TV+': "https://tv.apple.com/",
  'TV4 Play': "https://www.tv4play.se/",
  'Tele2 Play': "https://www.tele2.com/",
  'Telecine Amazon Channel': "https://www.primevideo.com/",
  'Telenet': "https://www.telenet.be/",
  'Telia Play': "https://www.teliaplay.se/",
  'The Roku Channel': "https://therokuchannel.roku.com/",
  'Timvision': "https://www.timvision.it/",
  'TriArt Play': "https://www.triartplay.se/",
  'Tubi TV': "https://tubitv.com/",
  'TvIgle': "https://tvigle.ru/",
  'U-NEXT': "https://video.unext.jp/",
  'UPC TV': "https://www.upc.ch/",
  'Universal+ Amazon Channel': "https://www.primevideo.com/",
  'Universcine': "https://www.universcine.com/",
  'Universcine Amazon Channel': "https://www.primevideo.com/",
  'VI movies and tv': "https://www.vimoviesandtv.com/",
  'VIVA by videofutur': "https://www.videofutur.com/",
  'Verleihshop': "https://www.verleihshop.de/",
  'Viaplay': "https://viaplay.com/",
  'Videobuster': "https://www.videobuster.de/",
  'Videoland': "https://www.videoland.com/",
  'Videoload': "https://www.videoload.de/",
  'Vidio': "https://www.vidio.com/",
  'WOW': "https://www.wowtv.co.uk/",
  'Watcha': "https://watcha.com/",
  'Yorck on Demand': "https://yorck.de/",
  'YouTube': "https://www.youtube.com/movies",
  'Youtube TV': "https://tv.youtube.com/",
  'Zee5': "https://www.zee5.com/",
  'blue TV': "https://www.bluetv.ch/",
  'filmingo': "https://filmingo.ch/",
  'fuboTV': "https://www.fubo.tv/",
  'maxdome Store': "https://www.maxdome.de/",
  'meJane': "https://mejane.com/",
  'wavve': "https://www.wavve.com/"
} as const

export type ProviderLink = keyof typeof providers_link

export function getProviderLink(key: ProviderLink): string {
  return providers_link[key] ?? "";
}